INSERT INTO policies (
    id,
    policy_number,
    policyholder_name,
    line_of_business,
    status,
    premium_amount,
    currency,
    effective_date,
    expiry_date,
    region,
    underwriter,
    flagged_for_review,
    created_at,
    updated_at
) VALUES
(
    RANDOM_UUID(),
    'POL-100001',
    'Acme Corporation',
    'PROPERTY',
    'ACTIVE',
    125000.00,
    'SGD',
    '2025-01-01',
    '2026-12-31',
    'Singapore',
    'James Wilson',
    FALSE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    RANDOM_UUID(),
    'POL-100002',
    'Pacific Trading Ltd',
    'CASUALTY',
    'ACTIVE',
    275000.00,
    'HKD',
    '2025-03-15',
    '2027-03-14',
    'Hong Kong',
    'Sarah Chen',
    FALSE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    RANDOM_UUID(),
    'POL-100003',
    'Tokyo Manufacturing Co',
    'MARINE',
    'EXPIRED',
    850000.00,
    'JPY',
    '2023-01-01',
    '2024-12-31',
    'Japan',
    'Michael Brown',
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    RANDOM_UUID(),
    'POL-100004',
    'Sydney Infrastructure Pty',
    'PROPERTY',
    'PENDING',
    1450000.00,
    'AUD',
    '2026-10-01',
    '2027-09-30',
    'Australia',
    'Emily Davis',
    FALSE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    RANDOM_UUID(),
    'POL-100005',
    'Bangkok Logistics Co',
    'CASUALTY',
    'CANCELLED',
    95000.00,
    'THB',
    '2024-06-01',
    '2025-05-31',
    'Thailand',
    'Daniel Smith',
    FALSE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    RANDOM_UUID(),
    'POL-100006',
    'Jakarta Energy Solutions',
    'A_AND_H',
    'ACTIVE',
    375000.00,
    'USD',
    '2026-01-01',
    '2026-12-31',
    'Indonesia',
    'Olivia Taylor',
    FALSE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    RANDOM_UUID(),
    'POL-100007',
    'Kuala Lumpur Holdings',
    'PROPERTY',
    'EXPIRED',
    215000.00,
    'USD',
    '2023-07-01',
    '2024-06-30',
    'Malaysia',
    'William Anderson',
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    RANDOM_UUID(),
    'POL-100008',
    'Manila Retail Group',
    'MARINE',
    'PENDING',
    675000.00,
    'USD',
    '2026-09-01',
    '2027-08-31',
    'Philippines',
    'Sophia Martinez',
    FALSE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    RANDOM_UUID(),
    'POL-100009',
    'Singapore Airlines Services',
    'A_AND_H',
    'ACTIVE',
    2250000.00,
    'SGD',
    '2026-02-01',
    '2027-01-31',
    'Singapore',
    'Robert Johnson',
    FALSE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
),
(
    RANDOM_UUID(),
    'POL-100010',
    'Hong Kong Shipping Ltd',
    'MARINE',
    'CANCELLED',
    510000.00,
    'HKD',
    '2025-04-01',
    '2026-03-31',
    'Hong Kong',
    'Emma Williams',
    TRUE,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
);